export const typeColors: { [key: string]: string } = {
    fire: "bg-orange-500",
    grass: "bg-green-500",
    water: "bg-blue-500",
    electric: "bg-yellow-500",
    psychic: "bg-pink-500",
    ice: "bg-cyan-500",
    dragon: "bg-purple-500",
    dark: "bg-gray-700",
    fairy: "bg-pink-300",
    normal: "bg-gray-400",
    fighting: "bg-red-600",
    flying: "bg-indigo-400",
    poison: "bg-purple-600",
    ground: "bg-yellow-600",
    rock: "bg-gray-600",
    bug: "bg-green-600",
    ghost: "bg-indigo-700",
    steel: "bg-gray-500",
};
  